/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestorinventario;

/**
 *
 * @author BICHO
 */
public class formInicio extends javax.swing.JFrame {

    /**
     * Creates new form formInicio
     */
    public formInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelLh = new javax.swing.JPanel();
        LblWelcome = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        itemIngresar = new javax.swing.JMenu();
        itemIngreso = new javax.swing.JMenuItem();
        itemCerrar = new javax.swing.JMenuItem();
        RolesMen = new javax.swing.JMenu();
        itemCrearRol = new javax.swing.JMenuItem();
        itemModificar = new javax.swing.JMenuItem();
        UsuariosMen = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLh.setBackground(new java.awt.Color(50, 137, 168));
        panelLh.setForeground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout panelLhLayout = new javax.swing.GroupLayout(panelLh);
        panelLh.setLayout(panelLhLayout);
        panelLhLayout.setHorizontalGroup(
            panelLhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        panelLhLayout.setVerticalGroup(
            panelLhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        LblWelcome.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 60)); // NOI18N
        LblWelcome.setText("Welcome");

        itemIngresar.setText("Ingreso");
        itemIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIngresarActionPerformed(evt);
            }
        });

        itemIngreso.setText("Iniciar");
        itemIngresar.add(itemIngreso);

        itemCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemCerrar.setText("Cerrar");
        itemIngresar.add(itemCerrar);

        barraMenu.add(itemIngresar);

        RolesMen.setText("Rol");

        itemCrearRol.setText("Crear Rol");
        RolesMen.add(itemCrearRol);

        itemModificar.setText("Modificar Rol");
        RolesMen.add(itemModificar);

        barraMenu.add(RolesMen);

        UsuariosMen.setText("Usuarios");
        barraMenu.add(UsuariosMen);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242)
                .addComponent(LblWelcome)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LblWelcome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblWelcome;
    private javax.swing.JMenu RolesMen;
    private javax.swing.JMenu UsuariosMen;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuItem itemCrearRol;
    private javax.swing.JMenu itemIngresar;
    private javax.swing.JMenuItem itemIngreso;
    private javax.swing.JMenuItem itemModificar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel panelLh;
    // End of variables declaration//GEN-END:variables
}
