/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.gestorinventario;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author BICHO
 */
public class formCategoria extends javax.swing.JFrame {

    /**
     * Creates new form formCategoria
     */
    public formCategoria() {
        initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDescripcionTipo = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        cmbBoxProv = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUniMedida = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtVenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCantMin = new javax.swing.JTextField();
        lblFabricante = new javax.swing.JLabel();
        cmbBoxFabri = new javax.swing.JComboBox<>();
        btnAddProv = new javax.swing.JButton();
        btnAddFab = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        lblCategoria = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        lblIdCategoria = new javax.swing.JLabel();
        txtIdTipos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbBoxCategoria = new javax.swing.JComboBox<>();
        cmbBoxGrupo = new javax.swing.JComboBox<>();
        txtNombreTipo = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnAddGrupo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorRemoved(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 52)); // NOI18N
        jLabel1.setText("TIPOS");

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 153));
        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jDesktopPane1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel3.setText("PROVEEDOR");

        cmbBoxProv.setEditable(true);
        cmbBoxProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxProvActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio Costo");

        jLabel5.setText("Precio Venta");

        jLabel6.setText("Unidad de Medida");

        jLabel7.setText("Cant. Min. en Stock");

        lblFabricante.setText("FABRICANTE");

        cmbBoxFabri.setEditable(true);
        cmbBoxFabri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxFabriActionPerformed(evt);
            }
        });

        btnAddProv.setText("+");
        btnAddProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProvActionPerformed(evt);
            }
        });

        btnAddFab.setText("+");
        btnAddFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFabActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cmbBoxProv, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtUniMedida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtCosto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtVenta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtCantMin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblFabricante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cmbBoxFabri, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnAddProv, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnAddFab, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBoxProv, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(txtCantMin))
                                .addGap(207, 207, 207))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(btnAddProv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(txtUniMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(cmbBoxFabri, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddFab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(285, Short.MAX_VALUE))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUniMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProv))
                .addGap(18, 18, 18)
                .addComponent(lblFabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxFabri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddFab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        txtUniMedida.getAccessibleContext().setAccessibleName("panelTipo");
        txtUniMedida.getAccessibleContext().setAccessibleDescription("");
        txtCosto.getAccessibleContext().setAccessibleName("panelTipo");
        txtCosto.getAccessibleContext().setAccessibleDescription("");
        txtVenta.getAccessibleContext().setAccessibleName("panelTipo");
        txtVenta.getAccessibleContext().setAccessibleDescription("");
        txtCantMin.getAccessibleContext().setAccessibleName("panelTipo");
        txtCantMin.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("CARACTERISTICAS", jDesktopPane1);
        jTabbedPane1.addTab("IMAGEN", jTabbedPane2);

        lblCategoria.setText("CATEGORIA");

        lblGrupo.setText("GRUPO");

        lblIdCategoria.setText("SKU");

        jLabel2.setText("NOMBRE");

        cmbBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRODUCTO", "SERVICIO" }));
        cmbBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxCategoriaActionPerformed(evt);
            }
        });

        cmbBoxGrupo.setEditable(true);

        lblDescripcion.setText("DESCRIPCION");

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnAddGrupo.setText("+");
        btnAddGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(206, 206, 206)
                                .addComponent(lblDescripcion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreTipo)
                                    .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblGrupo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDescripcionTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCategoria)
                    .addComponent(txtIdTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcionTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(lblGrupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddGrupo))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        txtDescripcionTipo.getAccessibleContext().setAccessibleName("panelTipo");
        txtDescripcionTipo.getAccessibleContext().setAccessibleDescription("");
        txtIdTipos.getAccessibleContext().setAccessibleName("panelTipo");
        txtIdTipos.getAccessibleContext().setAccessibleDescription("");
        txtNombreTipo.getAccessibleContext().setAccessibleName("panelTipo");
        txtNombreTipo.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void jPanel1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1AncestorRemoved
*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
/*
    private void cmbBoxFabriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxFabriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxFabriActionPerformed
*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                   File f = new File("Productos.txt");
                   
                   File j = new File("comboFabri.txt");
                   
        String sku = "";
    String nombre = "";
    String descripcion ="";
    String combo1 = (String)cmbBoxProv.getSelectedItem();
    String unidad = "";
    
         try {
                        FileWriter fw = new FileWriter(f, true);
                        BufferedWriter bw = new BufferedWriter(fw);
                        sku = txtIdTipos.getText();
                        nombre = txtNombreTipo.getText();
                        descripcion = txtDescripcionTipo.getText();
                        combo1 = (String)cmbBoxProv.getSelectedItem();
                        unidad = txtUniMedida.getText();
                        bw.write(sku);
                        bw.write("|");
                        bw.write(nombre);
                        bw.write("|");
                        bw.write(descripcion);
                        bw.write("|");
                        bw.write(unidad);
                        bw.write("|");
                        bw.write(combo1);
                        bw.write("\n");
                        bw.close();
                        JOptionPane.showMessageDialog(null, "INGRESO EXITOSO");
                    } catch (IOException ex) {
                        Logger.getLogger(formCategoria.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbBoxProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxProvActionPerformed

    private void cmbBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxCategoriaActionPerformed

    private void btnAddProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProvActionPerformed
File f = new File("comboData.txt");
        // TODO add your handling code here:
        loadComboBoxData(cmbBoxProv); // carga los datos en el comboBox
        //se agrega ActionListener al botón para agregar un nuevo proveedor
        btnAddProv.addActionListener(new ActionListener() {
            private Component frame;
            @Override
            public void actionPerformed(ActionEvent e) {
                // Obtener el texto del JComboBox
                String newItem = (String) cmbBoxProv.getSelectedItem();

                // Verificar que no esté vacío y que no esté ya en la lista
                if (newItem != null && !newItem.trim().isEmpty() && !containsItem(cmbBoxProv, newItem)) {
                    cmbBoxProv.addItem(newItem); // Agregar el nuevo elemento
                    saveComboBoxData(cmbBoxProv); // Guardar en el archivo
                    cmbBoxProv.setSelectedItem(""); // Limpiar el JComboBox
                } else {
                    JOptionPane.showMessageDialog(frame, "El elemento ya existe o está vacío.");
                }
            }

            // Método para verificar si el item ya existe en el JComboBox
            private boolean containsItem(JComboBox<String> comboBox, String item) {
                for (int i = 0; i < comboBox.getItemCount(); i++) {
                    if (comboBox.getItemAt(i).equals(item)) {
                        return true;
                    }
                }
                return false;
            }

        });
        }
        // Cargar datos desde el archivo
        private static void loadComboBoxData(JComboBox<String> cmbBoxProv) {
            cmbBoxProv.removeAllItems();
            try (BufferedReader reader = new BufferedReader(new FileReader(FILE_NAME))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    cmbBoxProv.addItem(line);
                }
            } catch (IOException e) {
                
            }
        }

        // Guardar datos en el archivo
        private static void saveComboBoxData(JComboBox<String> cmbBoxProv) {
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_NAME))) {
                for (int i = 0; i < cmbBoxProv.getItemCount(); i++) {
                    writer.write(cmbBoxProv.getItemAt(i));
                    writer.newLine(); // Nueva línea para cada elemento
                }
            } catch (IOException e) {

            }
        }
    /**
     * @param args the command line arguments
     */
 private static final String FILE_NAME = "comboData.txt"; // Nombre del archivo    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

    }//GEN-LAST:event_btnAddProvActionPerformed
public class Producto {
    String sku;
    String nombre;
    String descripcion;
    String unidad;
    String proveedor;

    // Constructor
    public Producto(String sku, String nombre, String descripcion, String unidad, String proveedor) {
        this.sku = sku;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.unidad = unidad;
        this.proveedor = proveedor;
    }

    // Getters y Setters (opcional)
    // ...
}
private final ArrayList<Producto> productos = new ArrayList<>();
private Producto buscarProducto(String sku) {
    for (Producto p : productos) { // Itera sobre cada producto en la lista
        if (p.sku.equals(sku)) { // Compara el SKU del producto actual con el SKU buscado
            return p; // Retorna el producto si se encuentra
        }
    }
    return null; // Retorna null si no se encuentra el producto
}

private static final String FILE_NAME2="comboGroup.txt";
   
    private void btnAddGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGrupoActionPerformed
        // TODO add your handling code here: 
    File f = new File("comboGroup.txt");
    // Carga los datos en el comboBox de grupos
    loadComboBoxGroup(cmbBoxGrupo); 

    // Agrega ActionListener al botón para agregar un nuevo grupo
    btnAddGrupo.addActionListener(new ActionListener() {
        private Component frame;
        @Override
        public void actionPerformed(ActionEvent e) {
            //Obtener texto del comboBox
            String newItem = (String) cmbBoxGrupo.getSelectedItem();
            // Verificar que no esté vacío y que no esté ya en la lista
                if (newItem != null && !newItem.trim().isEmpty() && !containsItem(cmbBoxGrupo, newItem)) {
                    cmbBoxGrupo.addItem(newItem); // Agregar el nuevo elemento
                    saveComboBoxGroup(cmbBoxGrupo); // Guardar en el archivo
                    cmbBoxGrupo.setSelectedItem(""); // Limpiar el JComboBox
                } else {
                    JOptionPane.showMessageDialog(frame, "El elemento ya existe o está vacío.");
                }
            }
    });
}

// Método para verificar si el item ya existe en el JComboBox
private boolean containsItem(JComboBox<String> comboBox, String item) {
    for (int u = 0; u < comboBox.getItemCount(); u++) {
        if (comboBox.getItemAt(u).equals(item)) {
            return true;
        }
    }
    return false;
}

// Cargar datos desde el archivo
private static void loadComboBoxGroup(JComboBox<String> cmbBox) {
    cmbBox.removeAllItems();
    try (BufferedReader reader = new BufferedReader(new FileReader(FILE_NAME2))) {
        String line2;
        while ((line2 = reader.readLine()) != null) {
            cmbBox.addItem(line2);
        }
    } catch (IOException e) {
        // Manejo de excepción
    }
}

// Guardar datos en el archivo
private static void saveComboBoxGroup(JComboBox<String> cmbBox) {
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_NAME2))) {
        for (int u = 0; u < cmbBox.getItemCount(); u++) {
            writer.write(cmbBox.getItemAt(u));
            writer.newLine(); // Nueva línea para cada elemento
        }
    } catch (IOException e) {
        // Manejo de excepción
    }

    }//GEN-LAST:event_btnAddGrupoActionPerformed
private void jPanel1AncestorRemoved(javax.swing.event.AncestorEvent evt) {
    // Lógica a ejecutar cuando el panel es removido
}

private void cmbBoxFabriActionPerformed(java.awt.event.ActionEvent evt) {
    // Lógica a ejecutar cuando se selecciona un elemento en cmbBoxFabri
}
private static final String FILE_NAME3="comboFabri.txt";

    private void btnAddFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFabActionPerformed
     
        // TODO add your handling code here: 
    
    // Carga los datos en el comboBox de grupos
    loadComboBoxFabri(cmbBoxFabri); 

    // Agrega ActionListener al botón para agregar un nuevo grupo
    btnAddFab.addActionListener(new ActionListener() {
        private Component frame;
        @Override
        public void actionPerformed(ActionEvent e) {
            //Obtener texto del comboBox
            String newItem = (String) cmbBoxFabri.getSelectedItem();
            // Verificar que no esté vacío y que no esté ya en la lista
                if (newItem != null && !newItem.trim().isEmpty() && !containsItem(cmbBoxFabri, newItem)) {
                    cmbBoxFabri.addItem(newItem); // Agregar el nuevo elemento
                    saveComboBoxFabri(cmbBoxFabri); // Guardar en el archivo
                    cmbBoxFabri.setSelectedItem(""); // Limpiar el JComboBox
                } else {
                    JOptionPane.showMessageDialog(frame, "El elemento ya existe o está vacío.");
                }
            }
    });
}

    // Método para verificar si el item ya existe en el JComboBox
    private boolean doesComboBoxcontainsItem(JComboBox<String> comboBox, String item) {
    for (int t = 0; t < comboBox.getItemCount(); t++) {
        if (comboBox.getItemAt(t).equals(item)) {
            return true;
        }
    }
    return false;
}

// Cargar datos desde el archivo
private static void loadComboBoxFabri(JComboBox<String> cmbBox) {
    cmbBox.removeAllItems();
    try (BufferedReader reader = new BufferedReader(new FileReader(FILE_NAME3))) {
        String line3;
        while ((line3 = reader.readLine()) != null) {
            cmbBox.addItem(line3);
        }
    } catch (IOException e) {
        // Manejo de excepción
    }
}

// Guardar datos en el archivo
private static void saveComboBoxFabri(JComboBox<String> cmbBox) {
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_NAME3))) {
        for (int t = 0; t< cmbBox.getItemCount(); t++) {
            writer.write(cmbBox.getItemAt(t));
            writer.newLine(); // Nueva línea para cada elemento
        }
    } catch (IOException e) {
        // Manejo de excepción
    }

    

    }//GEN-LAST:event_btnAddFabActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFab;
    private javax.swing.JButton btnAddGrupo;
    private javax.swing.JButton btnAddProv;
    public javax.swing.JComboBox<String> cmbBoxCategoria;
    public javax.swing.JComboBox<String> cmbBoxFabri;
    public javax.swing.JComboBox<String> cmbBoxGrupo;
    public javax.swing.JComboBox<String> cmbBoxProv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblIdCategoria;
    public javax.swing.JTextField txtCantMin;
    public javax.swing.JTextField txtCosto;
    public javax.swing.JTextField txtDescripcionTipo;
    public javax.swing.JTextField txtIdTipos;
    public javax.swing.JTextField txtNombreTipo;
    public javax.swing.JTextField txtUniMedida;
    public javax.swing.JTextField txtVenta;
    // End of variables declaration//GEN-END:variables
}